services:
  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.submit50:/app/.submit50
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_EMAIL=${GITHUB_EMAIL:-}
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: requirements.txt
    command: bash -c "/home/appuser/setup-credentials.sh && /bin/bash"
    stdin_open: true
    tty: true

  # Production service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
